# Welcome to Serverless!

service: chat-bot

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/State"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/FeedbackV2"

functions:
  fbverify:
    handler: handler.fbVerify
    events:
      - http:
          path: fbhook
          method: GET
          integration: lambda
  fbmessages:
    handler: handler.fbMessages
    events:
      - http:
          path: fbhook
          method: POST
          integration: lambda

plugins:
  - serverless-offline
